// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { z } from "npm:zod@^3.25.76";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search Puthiyam Products catalog by name/description with optional category filter. Returns active in-stock products.",
  inputSchema: {
    query: z.string().trim().default("").describe("Text to match in product name or description. Empty returns latest."),
    category: z.string().optional().describe("Optional category filter (exact match)."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("products").select("id,name,description,category,base_price,measurement_unit,is_on_sale,discount_amount,discount_type").eq("is_active", true).limit(limit);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch a single product with its variants and images by product id.",
  inputSchema: {
    product_id: z2.string().uuid().describe("Product UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const [{ data: product, error: pErr }, variants, images] = await Promise.all([
      supabase.from("products").select("*").eq("id", product_id).maybeSingle(),
      supabase.from("product_variants").select("*").eq("product_id", product_id),
      supabase.from("product_images").select("*").eq("product_id", product_id)
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!product) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    const payload = { product, variants: variants.data ?? [], images: images.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "puthiyam-products-mcp",
  title: "Puthiyam Products",
  version: "0.1.0",
  instructions: "Tools for the Puthiyam Products storefront. Use `search_products` to browse the catalog and `get_product` to fetch full details including variants and images.",
  tools: [search_products_default, get_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
